import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// A sidebar é gerada a partir da estrutura de pastas em `docs/`.
// Ordem e rótulos: `sidebar_position` no front matter e `_category_.json` em cada pasta.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
